export const ActionTypes = {
	USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
	USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
	USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
	USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
	DIALOG_CLOSING: 'DIALOG_CLOSING',

	// INSTRUMENTS
	INSTRUMENT_SELECT: 'INSTRUMENT_SELECT',
	INSTRUMENTS_FETCH_SUCCESS: 'INSTRUMENTS_FETCH_SUCCESS',
	INSTRUMENTS_FETCH_FAILURE: 'INSTRUMENTS_FETCH_FAILURE',
	INSTRUMENT_BIDS_ASKS_PRICE_FETCH_SUCCESS: 'INSTRUMENT_BIDS_ASKS_PRICE_FETCH_SUCCESS',
}
