export const ActionTypes = {
	USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
	USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
	USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
	DIALOG_CLOSING: 'DIALOG_CLOSING',
}
