export const ActionTypes = {
	USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
	USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
	USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
	USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
	DIALOG_CLOSING: 'DIALOG_CLOSING',

	// INSTRUMENTS
	INSTRUMENT_SELECT: 'INSTRUMENT_SELECT',
	INSTRUMENTS_FETCH_SUCCESS: 'INSTRUMENTS_FETCH_SUCCESS',
	INSTRUMENTS_FETCH_FAILURE: 'INSTRUMENTS_FETCH_FAILURE',
	INSTRUMENT_BIDS_ASKS_PRICE_FETCH_SUCCESS:
		'INSTRUMENT_BIDS_ASKS_PRICE_FETCH_SUCCESS',

	// FIAT
	FIAT_PURCHASE_REQUEST: 'FIAT_PURCHASE_REQUEST',
	FIAT_PURCHASE_SUCCESS: 'FIAT_PURCHASE_SUCCESS',
	FIAT_PURCHASE_FAILURE: 'FIAT_PURCHASE_FAILURE',
	FIAT_DEPOSIT_REQUEST: 'FIAT_DEPOSIT_REQUEST',
	FIAT_DEPOSIT_SUCCESS: 'FIAT_DEPOSIT_SUCCESS',
	FIAT_DEPOSIT_FAILURE: 'FIAT_DEPOSIT_FAILURE',

	// ORDERS
	PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
	PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
	PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',
}
